# Generated by Django 5.0.6 on 2024-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Status')),
                ('deadline', models.DateField(verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'ToDoTask',
                'verbose_name_plural': 'ToDoList',
                'db_table': 'toDoList',
            },
        ),
    ]
