# Generated by Django 5.0.6 on 2024-06-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_todolist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='full_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Full Description'),
        ),
    ]
